#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build/Publish

on:
  push:
    branches:
      - master

jobs:
  nightly-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0
          
      - name: Prepare
        id: prep
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1} 
          
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Build and push plugin registry image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          target: registry
          platforms: linux/amd64,linux/s390x
          tags: quay.io/aditi-che/che-plugin-registry:nightly,quay.io/aditi-che/che-plugin-registry:${{ steps.prep.outputs.short_sha1 }}
          push: true          
          #docker build -t che-plugin-registry -f ./build/dockerfiles/Dockerfile --target registry .
          #docker tag che-plugin-registry quay.io/eclipse/che-plugin-registry:nightly
          #docker push quay.io/eclipse/che-plugin-registry:nightly
          #docker tag che-plugin-registry quay.io/eclipse/che-plugin-registry:${SHORT_SHA1}
          #docker push quay.io/eclipse/che-plugin-registry:${SHORT_SHA1}
            
