#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Image Build PR check

on:   
  push:
      branches: 
        - master

jobs:
  image-build:
    strategy:
      matrix:
        dist: [ 'alpine', 'rhel' ]
    runs-on: ubuntu-20.04
    steps:
    - name: Clone source code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
  
    - name: image-build for alpine
      if: ${{ matrix.dist == 'alpine' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/Dockerfile
        target: registry
        platforms: linux/amd64,linux/s390x
        tags: che-plugin-registry-image
        cache-from: "quay.io/aditijadhav38/che-plugin-registry:nightly"
        push: false
        
    - name: image-build for alpine
      if: ${{ matrix.dist == 'rhel' }}
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./build/dockerfiles/rhel.Dockerfile
        target: registry
        platforms: linux/amd64,linux/s390x
        tags: che-plugin-registry-image
        push: false     
        
    - name: Create tar
      run: |
        docker create --name pluginRegistry che-plugin-registry-image sh
        mkdir root-dir
        docker cp pluginRegistry:/var/www/html/v3 root-dir/v3
        docker rm -f pluginRegistry
        cp root-dir/v3/plugins/index.json root-dir/index.json
        tar zcvf content-${{matrix.dist}}.tgz -C root-dir .
    - uses: actions/upload-artifact@v2
      with:
        name: plugin-registry-content-${{matrix.dist}}
        path: content-${{matrix.dist}}.tgz
  
