#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: test

on:
  push:
    branches:
      - master

jobs:
  nightly-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        
      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Prepare
        id: prep
        with:
          tag-sha: true
                
      - name: Build and push plugin registry image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/dockerfiles/Dockerfile
          platforms: linux/amd64,linux/s390x
          push: true
          tags: |
            quay.io/aditijadhav38/che-plugin-registry:nightly
            quay.io/aditijadhav38/che-plugin-registry:${{ steps.prep.outputs.tags }}

