#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release Che Plugin Registry

on:
  push:
    branches: 
      - master
    

jobs:
  release-build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source code
        uses: actions/checkout@v2
        
      - name: Prepare
        id: prep
        run: |
          SHORT_SHA1=$(git rev-parse --short HEAD)
          echo ::set-output name=short_sha1::${SHORT_SHA1}
          VERSION=$(head -n 1 VERSION)
          echo ::set-output name=version::${VERSION}
                    
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Quay.io
        uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      
      - name: Login to Docker Hub
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v2
        env: |
          IMAGE=che-plugin-registry
          DOCKERFILE_PATH=./build/dockerfiles/Dockerfile
        with:
          context: .
          file: ${DOCKERFILE_PATH}
          target: registry
          platforms: linux/amd64,linux/s390x
          tags: quay.io/aditijadhav38/${IMAGE}:${{ steps.prep.outputs.short_sha1 }},quay.io/aditijadhav38/${IMAGE}:${{ steps.prep.outputs.version }}
      
          #SHORT_SHA1=$(git rev-parse --short HEAD)
          #VERSION=$(head -n 1 VERSION)
          #IMAGE=che-plugin-registry
          #DOCKERFILE_PATH=./build/dockerfiles/Dockerfile
          #docker build -t ${IMAGE} -f ${DOCKERFILE_PATH} --target registry .
          #docker tag ${IMAGE} quay.io/eclipse/${IMAGE}:${SHORT_SHA1}
          #docker push quay.io/eclipse/${IMAGE}:${SHORT_SHA1}
          #docker tag ${IMAGE} quay.io/eclipse/${IMAGE}:${VERSION}
          #docker push quay.io/eclipse/${IMAGE}:${VERSION}
